### ISSUE TITLE
“Teachable Machine:Snake” - Browser freezes, restarts: Too much memory used via html5 "canvas" objects?

### ISSUE THREAD

**Issue by git-marc** [CodingTrain/website#3078] opened 2021-02-23 12:39 UTC
**“Teachable Machine:Snake” - Browser window freezes., restarts**
**Too much memory used via html5 "canvas" objects?**

__________________________________________
**THANKS FOR THE GREAT TUTORIAL(S)!!!**

First of all:
**Thanks a lot for "Coding train's" brilliant tutorials** –
they are extremely helpful and perfectly structured
to provide a "machine-learning" as well as "ml5 js", "p5 js" beginner such as me
with footage & the knowledge behind it!

__________________________________________
**MY PROBLEM (APPLE MACBOOK PRO & IPHONE)**

“Teachable Machine:Snake”
https://editor.p5js.org/codingtrain/sketches/tqoOkW_ai

Whilst running the tutorial:
Browser window ...
**MacBook Pro/Safari Browser**
• automatically reloads 
• message "This web page was reloaded because it was using significant memory"
**IPhone XS/Safari Browser**
• freezes

__________________________________________
**"BUG-TRACKING TRIES"**

Tracking some of the Webpage's elements 
(Apple Macbook Pro / Safari's Webdeveloper tool)

high amount of canvas objects 
- make runtime footage very large 
- Continiously created

Searching for the "canvas-object-creator" : 
I am not sure, probably "snake.js / function classifyVideo()"
called ...
• several times per frame 
• via "function gotResults(error, results) {"

__________________________________________
**"BUG-FIXES"?**

Just assuming that this might help –

How can i 
- delete all "obsolete, unused canvases" keeping just the current, displayed canvas?
or
- avoid constant new canvases (using just one canvas)?

I tried to find more "bug-related" information but did not succeed in fixing the problem yet
- Google, stackexchange: "Delete Canvas object", "Too many Canvas objects" 
- w3schools: "html5_canvas" 

__________________________________________
__________________________________________

Please help a digital noob (me!):
Any hint is greatly appreciated!

Best Regards
Marc

**Comment by KobeLiesenborgs** [comment] 2022-05-16 20:12
Hi Marc!

Unfortunately with the big amount of videos it is near impossible to keep everything up to date that deprecates.
That being said you can always add a community contribution that has an updated version!

In this case specifically the issue is out of scope I fear.

P.S. you should join [our community discord](https://thecodingtrain.com/discord) for questions and remarks you might have in the future!

**Closed by KobeLiesenborgs** 2022-05-16 20:12 UTC
Labels: out of scope
